import { useEffect } from "react";
import { Link } from "wouter";
import { Clock3, Gamepad2, Lightbulb, Play, Trophy } from "lucide-react";
import { MobileNav } from "@/components/MobileNav";
import { BottomAd, SideAds } from "@/components/AdSense";
import { setPageSeo } from "@/lib/pageSeo";
import { useLanguage } from "@/hooks/useLanguage";

const CONTENT = {
  pt: { title: "Como Jogar o Jogo do Cronômetro", intro: "Aprenda a jogar o T3:MP:00, o jogo do tempo em que você precisa parar o relógio exatamente no valor sorteado.", objective: "O objetivo do jogo do tempo", objectiveText: "Neste jogo do relógio, um tempo-alvo é sorteado no formato minutos, segundos e centésimos. Cada jogador inicia sua tentativa com o contador visível ou oculto, conforme a configuração da sala. Vence quem parar o cronômetro mais perto do valor solicitado.", steps: [["Entre na sala", "Digite seu apelido e crie uma sala ou use o código enviado pelo líder."], ["Veja o tempo-alvo", "Todos recebem o mesmo número para tentar reproduzir."], ["Pare o cronômetro", "No celular, toque na área do jogo. No computador, pressione a barra de espaço."], ["Compare os resultados", "O ranking mostra o tempo de cada jogador e sua diferença para o alvo."]], tips: ["Conte mentalmente em um ritmo constante.", "Use o som ou uma batida regular como referência.", "O host pode escolher se o contador fica visível durante a tentativa."], play: "Jogar agora" },
  en: { title: "How to Play the Timer Game", intro: "Try to stop the timer exactly at the drawn target and finish with the smallest difference.", objective: "Objective", objectiveText: "A target time is drawn in minutes, seconds and hundredths. Each player starts without seeing the running timer. The closest stop wins.", steps: [["Join the room", "Enter your nickname and create a room or use the host's code."], ["See the target", "Everyone receives the same time to reproduce."], ["Stop the timer", "Tap the game area on mobile or press Space on a computer."], ["Compare results", "The ranking shows every time and its difference from the target."]], tips: ["Count mentally at a steady rhythm.", "Wait for the countdown to finish.", "The running timer stays hidden."], play: "Play now" },
  es: { title: "Cómo Jugar al Juego del Cronómetro", intro: "Intenta detener el cronómetro exactamente en el tiempo sorteado y termina con la menor diferencia.", objective: "El objetivo", objectiveText: "Se sortea un tiempo objetivo en minutos, segundos y centésimas. Cada jugador intenta detenerlo sin ver el tiempo. Gana quien quede más cerca.", steps: [["Entra en la sala", "Escribe tu apodo y crea una sala o usa el código del líder."], ["Mira el objetivo", "Todos reciben el mismo tiempo para reproducir."], ["Detén el cronómetro", "Toca el área del juego en móvil o pulsa Espacio en computadora."], ["Compara resultados", "El ranking muestra cada tiempo y su diferencia con el objetivo."]], tips: ["Cuenta mentalmente con un ritmo constante.", "Espera a que termine la cuenta atrás.", "El cronómetro permanece oculto."], play: "Jugar ahora" },
};

export default function ComoJogarCronometro() {
  const { lang } = useLanguage(); const language = lang === "en" || lang === "es" ? lang : "pt"; const c = CONTENT[language];
  const canonical = language === "en" ? "/en/how-to-play/timer-game" : language === "es" ? "/es/como-jugar/juego-del-cronometro" : "/como-jogar/cronometro";
  useEffect(() => { setPageSeo({ title: language === "pt" ? "Jogo do Tempo e Jogo do Cronômetro: Como Jogar | TikJogos" : `${c.title} | TikJogos`, description: c.intro, canonical: `https://tikjogos.com.br${canonical}`, keywords: language === "pt" ? "jogo do tempo, jogo do cronômetro, jogo do relógio, jogo de parar o cronômetro, T3:MP:00" : undefined }); window.scrollTo(0, 0); }, [canonical, c, language]);
  return <div className="min-h-screen bg-[#1a1b2e] text-white"><MobileNav/><SideAds/><BottomAd/><main className="mx-auto max-w-4xl space-y-12 px-4 py-12 md:py-20">
    <header className="text-center"><span className="inline-flex items-center gap-2 rounded-full border border-cyan-400/30 bg-cyan-500/10 px-4 py-2 text-xs font-black uppercase tracking-[.18em] text-cyan-300"><Clock3 className="h-4 w-4"/> Guia oficial</span><h1 className="mt-5 text-4xl font-black md:text-6xl">{c.title}</h1><p className="mx-auto mt-5 max-w-2xl text-lg text-slate-300">{c.intro}</p><div className="mx-auto mt-7 w-fit rounded-2xl border-2 border-cyan-400/40 bg-[#080d19] px-6 py-3 font-mono text-3xl font-black tracking-wider text-cyan-300"><span className="text-slate-400">T3:</span>MP:00</div></header>
    <section className="rounded-3xl border border-[#343854] bg-[#242642] p-6 md:p-8"><h2 className="flex items-center gap-3 text-2xl font-black"><Trophy className="text-yellow-400"/> {c.objective}</h2><p className="mt-4 leading-relaxed text-slate-300">{c.objectiveText}</p></section>
    {language === "pt" && <section className="rounded-3xl border border-cyan-400/20 bg-cyan-500/10 p-6 md:p-8"><h2 className="text-2xl font-black">Jogo do tempo, cronômetro ou relógio: como funciona?</h2><p className="mt-4 leading-relaxed text-slate-300">Conhecido como <strong className="text-white">jogo do tempo</strong>, <strong className="text-white">jogo do cronômetro</strong> ou <strong className="text-white">jogo do relógio</strong>, o desafio é simples: inicie a contagem e tente pará-la no instante exato indicado na tela. Você pode jogar sozinho para treinar ou criar uma sala para comparar sua precisão com a dos amigos.</p></section>}
    <section><h2 className="mb-5 flex items-center gap-3 text-2xl font-black"><Gamepad2 className="text-cyan-400"/> Passo a passo</h2><div className="grid gap-4 md:grid-cols-2">{c.steps.map(([title, text], i) => <article key={title} className="rounded-2xl border border-cyan-400/20 bg-cyan-500/10 p-5"><span className="text-3xl font-black text-cyan-400">{i + 1}</span><h3 className="mt-2 font-black">{title}</h3><p className="mt-2 text-sm leading-relaxed text-slate-300">{text}</p></article>)}</div></section>
    <section><h2 className="mb-5 flex items-center gap-3 text-2xl font-black"><Lightbulb className="text-yellow-400"/> Dicas</h2><div className="grid gap-4 md:grid-cols-3">{c.tips.map(t => <p key={t} className="rounded-2xl border border-[#343854] bg-[#242642] p-5 text-sm text-slate-300">{t}</p>)}</div></section>
    {language === "pt" && <div className="space-y-10">
      <section className="space-y-6"><h2 className="text-3xl font-black md:text-4xl">O que o jogo do cronômetro pode desenvolver?</h2>
        <article><h3 className="text-xl font-black text-cyan-300">Percepção e estimativa de tempo</h3><p className="mt-3 leading-relaxed text-slate-300">Nosso cérebro conta com mecanismos internos que ajudam a estimar a duração dos acontecimentos. O jogo do cronômetro coloca essa capacidade à prova ao pedir que você identifique a passagem de um determinado intervalo — como 10 segundos — sem consultar um relógio. Com a prática, o exercício pode ajudar a aprimorar a percepção e a estimativa de intervalos temporais.</p></article>
        <article><h3 className="text-xl font-black text-cyan-300">Foco e atenção</h3><p className="mt-3 leading-relaxed text-slate-300">Para acertar o momento de parar o cronômetro, é necessário manter a atenção concentrada na passagem dos segundos e evitar distrações. Isso transforma uma tarefa simples em um pequeno exercício de concentração, no qual você precisa permanecer focado em uma única atividade mental durante todo o desafio.</p></article>
        <article><h3 className="text-xl font-black text-cyan-300">Autocontrole e tomada de decisão</h3><p className="mt-3 leading-relaxed text-slate-300">Parar o cronômetro antes da hora pode ser uma reação impulsiva. Esperar pelo momento que você considera correto exige controle da resposta imediata e paciência. Dessa forma, o jogo também envolve habilidades relacionadas à autorregulação e ao controle de impulsos.</p></article>
      </section>
      <section className="space-y-6"><h2 className="text-3xl font-black md:text-4xl">Para quem o teste de percepção temporal pode ser útil?</h2>
        <article><h3 className="text-xl font-black text-cyan-300">Músicos e artistas</h3><p className="mt-3 leading-relaxed text-slate-300">Ritmo e percepção temporal fazem parte da rotina de músicos, cantores e dançarinos. Ter uma boa noção de duração ajuda a manter o compasso e executar movimentos ou sons no momento adequado, mesmo sem depender constantemente de um metrônomo ou outra referência externa.</p></article>
        <article><h3 className="text-xl font-black text-cyan-300">Atletas e treinadores</h3><p className="mt-3 leading-relaxed text-slate-300">A percepção do tempo também aparece em diversas situações esportivas. Atletas precisam controlar ritmo, pausas, intervalos de recuperação e duração de determinadas atividades. Corredores, por exemplo, podem usar a percepção temporal para controlar o próprio ritmo, enquanto treinadores precisam administrar períodos de treino e descanso.</p></article>
        <article><h3 className="text-xl font-black text-cyan-300">Palestrantes e apresentadores</h3><p className="mt-3 leading-relaxed text-slate-300">Durante uma apresentação, nem sempre é possível olhar para o relógio. Desenvolver uma noção mais intuitiva da passagem do tempo pode ajudar palestrantes e apresentadores a controlar melhor a duração de suas falas, distribuir o conteúdo e evitar ultrapassar o tempo disponível.</p></article>
        <article><h3 className="text-xl font-black text-cyan-300">Quem quer treinar a concentração</h3><p className="mt-3 leading-relaxed text-slate-300">Por ter uma mecânica simples, o jogo pode servir como um exercício acessível para quem deseja praticar atenção. A tarefa é objetiva: acompanhar mentalmente a passagem do tempo e decidir quando interromper o cronômetro. Isso permite trabalhar a concentração sem exigir uma atividade complexa.</p></article>
      </section>
      <section className="space-y-6"><h2 className="text-3xl font-black md:text-4xl">Onde essa habilidade aparece no dia a dia?</h2>
        <article><h3 className="text-xl font-black text-cyan-300">Cozinha e atividades cotidianas</h3><p className="mt-3 leading-relaxed text-slate-300">Muitas tarefas dependem de uma estimativa aproximada de tempo. Saber quando verificar uma comida, calcular quanto tempo passou desde o início de uma atividade ou estimar a duração de uma pausa são exemplos comuns. Uma percepção temporal mais desenvolvida pode facilitar essas situações.</p></article>
        <article><h3 className="text-xl font-black text-cyan-300">Organização e produtividade</h3><p className="mt-3 leading-relaxed text-slate-300">Ter uma noção realista de quanto tempo uma tarefa costuma levar é importante para planejar o dia. Quando alguém calcula mal a duração de uma atividade, pode acabar acumulando atrasos ou deixando pouco tempo para concluir outras tarefas. Praticar a estimativa temporal pode ajudar a perceber melhor essas diferenças.</p></article>
        <article><h3 className="text-xl font-black text-cyan-300">Presença e atenção ao momento</h3><p className="mt-3 leading-relaxed text-slate-300">Prestar atenção conscientemente à passagem dos segundos também pode funcionar como um exercício de presença. Durante a partida, você precisa deixar outras distrações de lado e concentrar-se exclusivamente na percepção do tempo, criando uma experiência breve de atenção focada.</p></article>
      </section>
      <section className="space-y-6"><h2 className="text-3xl font-black md:text-4xl">Como melhorar seu desempenho?</h2>
        <article><h3 className="text-xl font-black text-cyan-300">Escolha uma estratégia de contagem</h3><p className="mt-3 leading-relaxed text-slate-300">Você pode contar mentalmente usando um ritmo constante, como “um-Mississippi, dois-Mississippi”, ou simplesmente acompanhar os segundos internamente. Teste diferentes métodos e escolha aquele que permite manter uma cadência mais consistente.</p></article>
        <article><h3 className="text-xl font-black text-cyan-300">Aumente a dificuldade aos poucos</h3><p className="mt-3 leading-relaxed text-slate-300">Começar com intervalos curtos pode facilitar a adaptação. Experimente primeiro 5 segundos e, conforme ganhar confiança, avance para 10, 15 segundos ou períodos maiores. Intervalos mais longos tendem a ser mais difíceis de estimar com precisão.</p></article>
        <article><h3 className="text-xl font-black text-cyan-300">Mantenha uma rotina de prática</h3><p className="mt-3 leading-relaxed text-slate-300">A consistência é mais importante do que sessões longas. Jogar regularmente permite comparar seus resultados e perceber como sua capacidade de estimar determinados intervalos evolui ao longo do tempo.</p></article>
      </section>
    </div>}
    <div className="text-center"><Link href="/" className="inline-flex items-center gap-2 rounded-2xl bg-cyan-400 px-9 py-5 text-xl font-black text-slate-950"><Play className="fill-current"/> {c.play}</Link></div>
  </main></div>;
}
