import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, Check, Copy, Flag, Forward, LogOut, Play, RotateCcw, SkipForward, Trophy, Vote, X } from "lucide-react";
import { GameIdentityLayout } from "@/components/GameIdentityLayout";
import { MobileNav } from "@/components/MobileNav";
import { cn } from "@/lib/utils";

type Answer = { category: string; value: string; status: "pending" | "skipped" | "answered" | "noAnswer" };
type Player = { uid: string; name: string; connected: boolean; characterIndex: number; answers: Answer[]; currentIndex: number; finished: boolean; score: number };
type Room = { code: string; hostId: string; status: "waiting" | "playing" | "voting" | "results"; letter: string; players: Player[]; votes: Record<string, Record<string, boolean>> };

export default function StopGame() {
  const roomCode = (new URLSearchParams(window.location.search).get("room") || sessionStorage.getItem("stop_room_code") || "").toUpperCase();
  const playerId = useRef(sessionStorage.getItem("stop_player_id") || crypto.randomUUID());
  const [room, setRoom] = useState<Room | null>(null);
  const [value, setValue] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  sessionStorage.setItem("stop_player_id", playerId.current);

  const request = useCallback(async (path: string, body?: object) => {
    const response = await fetch(path, body ? { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) } : undefined);
    const data = await response.json(); if (!response.ok) throw new Error(data.error || "Não foi possível continuar."); return data;
  }, []);

  useEffect(() => {
    if (!roomCode) { window.location.replace("/"); return; }
    let active = true;
    const load = async () => { try { const data = await request(`/api/stop/rooms/${roomCode}`); if (active) setRoom(data); } catch (e: any) { if (active) setError(e.message); } };
    void load(); const timer = window.setInterval(load, 900); return () => { active = false; window.clearInterval(timer); };
  }, [roomCode, request]);

  const act = async (endpoint: string, body: object = {}) => { if (!room) return; setBusy(true); setError(""); try { setRoom(await request(`/api/stop/rooms/${room.code}/${endpoint}`, body)); } catch (e: any) { setError(e.message); } finally { setBusy(false); } };
  const me = room?.players.find(player => player.uid === playerId.current);
  const isHost = room?.hostId === playerId.current;
  const leave = async () => { if (room) fetch(`/api/stop/rooms/${room.code}/leave`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ playerId: playerId.current }) }).catch(() => {}); sessionStorage.removeItem("stop_room_code"); window.location.href = "/"; };
  const submit = async (action: "answer" | "skip" | "noAnswer") => { await act("answer", { playerId: playerId.current, action, value }); if (action === "answer") setValue(""); };

  if (!room || !me) return <div className="min-h-screen bg-[#1a1e2a] text-white"><MobileNav/><div className="grid min-h-[75vh] place-items-center text-center"><div><Forward className="mx-auto h-12 w-12 animate-pulse text-violet-300"/><p className="mt-4 font-bold text-slate-400">{error || "Entrando na sala..."}</p></div></div></div>;
  const current = me.answers[me.currentIndex];
  const answered = me.answers.filter(answer => answer.status === "answered" || answer.status === "noAnswer").length;
  const votingAnswers = room.players.flatMap(player => player.answers.map((answer, index) => ({ player, answer, index })).filter(item => item.answer.status === "answered" || item.answer.status === "noAnswer"));
  const ranking = [...room.players].sort((a, b) => b.score - a.score);

  const navigation = room.status === "waiting" ? undefined : () => act("lobby", { playerId: playerId.current });
  return <div className="min-h-screen bg-[#1a1e2a] text-white"><MobileNav/><div className="flex justify-center"><GameIdentityLayout players={room.players} userId={playerId.current} hostId={room.hostId} detail={player => <p className="mt-1 text-[9px] font-black uppercase text-violet-300">{room.status === "results" ? `${player.score ?? 0} pontos` : player.finished ? "Pronto para STOP" : "Jogando"}</p>} onBackToLobby={isHost ? navigation : undefined} onExit={leave}>
    <header className="flex items-center justify-between border-b border-slate-700/60 pb-5"><button onClick={() => navigator.clipboard.writeText(room.code)} className="text-left"><p className="text-[10px] font-black uppercase tracking-[.2em] text-slate-500">Código da sala</p><strong className="mt-1 flex items-center gap-2 font-mono text-3xl font-black tracking-widest text-amber-400">{room.code}<Copy className="h-4 w-4"/></strong></button>{room.letter && <div className="grid h-16 w-16 place-items-center rounded-2xl border-2 border-violet-400 bg-violet-500/20 text-4xl font-black text-white">{room.letter}</div>}</header>

    {room.status === "waiting" && <section className="flex flex-1 flex-col items-center justify-center py-8 text-center"><div className="grid h-24 w-24 place-items-center rounded-3xl border-2 border-violet-400/40 bg-violet-500/15 text-5xl font-black">S</div><p className="mt-5 text-[10px] font-black uppercase tracking-[.22em] text-violet-300">Novo jogo · Beta</p><h1 className="mt-2 text-4xl font-black">STOP em sequência</h1><p className="mt-3 max-w-xl text-slate-400">Uma categoria por vez. Responda, avance e volte às que você pulou antes de gritar STOP.</p><div className="tj-inset mt-7 w-full max-w-xl p-4"><div className="grid grid-cols-5 gap-2">{Array.from({length:10},(_,index)=>{const taken=room.players.some(player=>player.uid!==me.uid&&player.characterIndex===index);return <button key={index} onClick={()=>!taken&&act("character",{playerId:playerId.current,characterIndex:index})} disabled={taken} className={cn("aspect-square rounded-xl border-2 font-black",me.characterIndex===index?"border-violet-400 bg-violet-500/20":"border-slate-700 bg-slate-900",taken&&"opacity-25")}>{index+1}</button>})}</div></div>{isHost?<button onClick={()=>act("start",{playerId:playerId.current})} disabled={busy||room.players.length<2} className="mt-6 h-16 w-full max-w-xl rounded-2xl border-b-4 border-violet-800 bg-violet-500 text-lg font-black disabled:opacity-40"><Play className="mr-2 inline h-5 w-5 fill-current"/>INICIAR PARTIDA</button>:<div className="tj-inset mt-6 w-full max-w-xl py-5 font-black text-violet-300">Aguardando o capitão...</div>}</section>}

    {room.status === "playing" && <section className="flex flex-1 flex-col py-6"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-slate-500">Seu progresso</p><p className="mt-1 font-black text-violet-300">{answered}/{me.answers.length} categorias concluídas</p></div><div className="flex gap-1">{me.answers.map((answer,index)=><span key={index} className={cn("h-2 w-7 rounded-full",answer.status==="answered"?"bg-emerald-400":answer.status==="noAnswer"?"bg-slate-500":answer.status==="skipped"?"bg-amber-400":"bg-slate-700")}/>)}</div></div><div className="flex flex-1 flex-col items-center justify-center py-8 text-center"><p className="text-[10px] font-black uppercase tracking-[.22em] text-violet-300">Categoria {me.currentIndex+1}</p><h1 className="mt-3 text-4xl font-black sm:text-6xl">{current.category}</h1>{current.status==="skipped"&&<p className="mt-3 rounded-full bg-amber-400/10 px-4 py-2 text-xs font-black text-amber-300">Você pulou esta categoria. Agora responda ou marque que não existe.</p>}<div className="tj-inset mt-8 w-full max-w-2xl p-5"><div className="flex items-center gap-3"><span className="grid h-14 w-14 place-items-center rounded-xl bg-violet-500 text-3xl font-black">{room.letter}</span><input autoFocus value={value} onChange={event=>setValue(event.target.value)} onKeyDown={event=>event.key==="Enter"&&value.trim()&&submit("answer")} placeholder={`${current.category} com ${room.letter}...`} className="h-14 min-w-0 flex-1 rounded-xl border-2 border-slate-700 bg-slate-950 px-4 text-lg font-black outline-none focus:border-violet-400"/></div><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>submit("skip")} disabled={busy} className="h-13 rounded-xl border-2 border-slate-700 bg-slate-900 font-black text-slate-300"><SkipForward className="mr-2 inline h-5 w-5"/>PULAR</button><button onClick={()=>submit("answer")} disabled={busy||!value.trim()} className="h-13 rounded-xl border-b-4 border-violet-800 bg-violet-500 font-black disabled:opacity-40">PRÓXIMO <Forward className="ml-2 inline h-5 w-5"/></button></div>{current.status==="skipped"&&<button onClick={()=>submit("noAnswer")} className="mt-3 h-11 w-full rounded-xl border border-amber-400/30 bg-amber-400/10 text-sm font-black text-amber-300">NÃO EXISTE RESPOSTA</button>}</div></div>{me.finished?<button onClick={()=>act("stop",{playerId:playerId.current})} className="h-16 rounded-2xl border-b-4 border-rose-800 bg-rose-500 text-2xl font-black"><Flag className="mr-2 inline h-6 w-6 fill-current"/>STOP!</button>:<p className="text-center text-xs font-bold text-slate-500">O STOP será liberado quando todas as categorias forem resolvidas.</p>}</section>}

    {room.status === "voting" && <section className="flex-1 py-6"><div className="text-center"><Vote className="mx-auto h-10 w-10 text-violet-300"/><h1 className="mt-3 text-3xl font-black">Validação da mesa</h1><p className="mt-2 text-slate-400">Valide a palavra ou confirme se realmente não existe uma resposta.</p></div><div className="mt-6 max-h-[480px] space-y-2 overflow-y-auto pr-1">{votingAnswers.map(({player,answer,index})=>{const key=`${player.uid}:${index}`;const mine=room.votes[key]?.[me.uid];return <article key={key} className="tj-player-card flex items-center gap-3 p-3"><div className="min-w-0 flex-1"><p className="text-[9px] font-black uppercase text-slate-500">{answer.category} · {player.name}</p><strong className={cn("text-lg",answer.status==="noAnswer"?"text-amber-300":"text-white")}>{answer.status==="noAnswer"?`Sem resposta com ${room.letter}`:answer.value}</strong></div>{player.uid===me.uid?<span className="text-xs font-bold text-slate-500">Sua resposta</span>:<div className="flex gap-2"><button onClick={()=>act("vote",{voterId:me.uid,playerId:player.uid,categoryIndex:index,valid:false})} className={cn("grid h-10 w-10 place-items-center rounded-xl border",mine===false?"border-rose-400 bg-rose-500/20 text-rose-300":"border-slate-700 bg-slate-900 text-slate-500")}><X/></button><button onClick={()=>act("vote",{voterId:me.uid,playerId:player.uid,categoryIndex:index,valid:true})} className={cn("grid h-10 w-10 place-items-center rounded-xl border",mine===true?"border-emerald-400 bg-emerald-500/20 text-emerald-300":"border-slate-700 bg-slate-900 text-slate-500")}><Check/></button></div>}</article>})}</div>{isHost?<button onClick={()=>act("finish",{playerId:me.uid})} className="mt-5 h-16 w-full rounded-2xl border-b-4 border-violet-800 bg-violet-500 text-lg font-black">ENCERRAR VOTAÇÃO</button>:<p className="tj-inset mt-5 py-4 text-center font-bold text-slate-400">O capitão encerrará a votação.</p>}</section>}

    {room.status === "results" && <section className="flex flex-1 flex-col items-center justify-center py-8 text-center"><Trophy className="h-16 w-16 text-amber-300"/><p className="mt-4 text-[10px] font-black uppercase tracking-[.22em] text-amber-300">Resultado da rodada</p><h1 className="mt-2 text-4xl font-black">{ranking[0]?.name} venceu!</h1><div className="mt-7 w-full max-w-xl space-y-2">{ranking.map((player,index)=><div key={player.uid} className={cn("tj-player-card flex items-center p-4",index===0&&"is-current")}><strong className="w-10 text-xl text-amber-300">#{index+1}</strong><span className="flex-1 text-left font-black">{player.name}</span><span className="font-black text-violet-300">{player.score} pts</span></div>)}</div>{isHost?<button onClick={()=>act("lobby",{playerId:me.uid})} className="mt-7 h-16 w-full max-w-xl rounded-2xl border-b-4 border-violet-800 bg-violet-500 text-lg font-black"><RotateCcw className="mr-2 inline h-5 w-5"/>NOVA PARTIDA</button>:<p className="tj-inset mt-7 w-full max-w-xl py-4 font-bold text-slate-400">Aguardando o capitão...</p>}</section>}
    {error&&<p className="rounded-xl border border-rose-400/30 bg-rose-500/10 p-3 text-center font-bold text-rose-300">{error}</p>}
  </GameIdentityLayout></div></div>;
}
