export type AproximacaoQuestionEntry = {
  text: string;
  answer: number;
  unit: string;
};

/**
 * Segunda leva editorial do Aproximação.
 * Fatos que mudam com o tempo levam o ano de referência no enunciado.
 */
export const APROXIMACAO_QUESTIONS_2026: AproximacaoQuestionEntry[] = [
  // Brasil, televisão e cultura nacional (18)
  { text: "Em que ano estreou a primeira edição do Big Brother Brasil?", answer: 2002, unit: "ano" },
  { text: "Quantas edições do BBB haviam sido concluídas ao final de 2025?", answer: 25, unit: "edições" },
  { text: "Quantos participantes entraram no BBB 25?", answer: 24, unit: "participantes" },
  { text: "Em que ano a TV Globo foi inaugurada?", answer: 1965, unit: "ano" },
  { text: "Quantos episódios teve a novela Avenida Brasil?", answer: 179, unit: "episódios" },
  { text: "Em que ano estreou a novela original Vale Tudo?", answer: 1988, unit: "ano" },
  { text: "Quantos episódios teve a novela original Pantanal, exibida em 1990?", answer: 216, unit: "episódios" },
  { text: "Em que ano o programa Domingão do Faustão estreou na Globo?", answer: 1989, unit: "ano" },
  { text: "Em que ano estreou o programa Castelo Rá-Tim-Bum?", answer: 1994, unit: "ano" },
  { text: "Quantos episódios foram produzidos de Castelo Rá-Tim-Bum?", answer: 90, unit: "episódios" },
  { text: "Em que ano a apresentadora Xuxa estreou o Xou da Xuxa?", answer: 1986, unit: "ano" },
  { text: "Quantos integrantes formavam a banda Mamonas Assassinas?", answer: 5, unit: "integrantes" },
  { text: "Em que ano a música Evidências foi lançada por Chitãozinho & Xororó?", answer: 1990, unit: "ano" },
  { text: "Em que ano o grupo É o Tchan lançou o álbum Na Cabeça e na Cintura?", answer: 1996, unit: "ano" },
  { text: "Quantas regiões oficiais tem o Brasil?", answer: 5, unit: "regiões" },
  { text: "Quantas unidades federativas o Brasil possui contando o Distrito Federal?", answer: 27, unit: "unidades federativas" },
  { text: "Em que ano Brasília foi inaugurada como capital do Brasil?", answer: 1960, unit: "ano" },
  { text: "Quantos degraus tem a escadaria do Santuário da Penha, no Rio de Janeiro?", answer: 382, unit: "degraus" },

  // Cinema brasileiro e premiações recentes (18)
  { text: "Em que ano o filme Central do Brasil chegou aos cinemas?", answer: 1998, unit: "ano" },
  { text: "Quantas indicações ao Oscar Central do Brasil recebeu?", answer: 2, unit: "indicações" },
  { text: "Em que ano Cidade de Deus foi lançado no Brasil?", answer: 2002, unit: "ano" },
  { text: "Quantas indicações ao Oscar Cidade de Deus recebeu?", answer: 4, unit: "indicações" },
  { text: "Quantos minutos dura Cidade de Deus?", answer: 130, unit: "minutos" },
  { text: "Em que ano Tropa de Elite chegou aos cinemas?", answer: 2007, unit: "ano" },
  { text: "Quantos minutos dura Tropa de Elite?", answer: 115, unit: "minutos" },
  { text: "Em que ano O Auto da Compadecida chegou aos cinemas?", answer: 2000, unit: "ano" },
  { text: "Quantos minutos dura O Auto da Compadecida?", answer: 104, unit: "minutos" },
  { text: "Em que ano Minha Mãe É uma Peça chegou aos cinemas?", answer: 2013, unit: "ano" },
  { text: "Quantos filmes compõem a trilogia Minha Mãe É uma Peça?", answer: 3, unit: "filmes" },
  { text: "Em que ano Bacurau foi lançado comercialmente no Brasil?", answer: 2019, unit: "ano" },
  { text: "Quantos minutos dura Bacurau?", answer: 131, unit: "minutos" },
  { text: "Quantas indicações ao Oscar Ainda Estou Aqui recebeu em 2025?", answer: 3, unit: "indicações" },
  { text: "Quantos Oscars Ainda Estou Aqui venceu em 2025?", answer: 1, unit: "Oscar" },
  { text: "Qual foi o número da cerimônia do Oscar realizada em 2025?", answer: 97, unit: "ª edição" },
  { text: "Quantos filmes concorreram a Melhor Filme no Oscar de 2025?", answer: 10, unit: "filmes" },
  { text: "Quantos Oscars o filme Anora venceu em 2025?", answer: 5, unit: "Oscars" },

  // Hollywood e franquias (18)
  { text: "Quantos minutos dura o filme Barbie?", answer: 114, unit: "minutos" },
  { text: "Quantos minutos dura o filme Oppenheimer?", answer: 180, unit: "minutos" },
  { text: "Quantos Oscars Oppenheimer venceu?", answer: 7, unit: "Oscars" },
  { text: "Quantos minutos dura Avatar: O Caminho da Água?", answer: 192, unit: "minutos" },
  { text: "Em que ano o primeiro filme Avatar foi lançado?", answer: 2009, unit: "ano" },
  { text: "Quantos filmes formam a saga principal de Harry Potter?", answer: 8, unit: "filmes" },
  { text: "Em que ano Harry Potter e a Pedra Filosofal chegou aos cinemas?", answer: 2001, unit: "ano" },
  { text: "Quantos filmes formam a trilogia O Senhor dos Anéis dirigida por Peter Jackson?", answer: 3, unit: "filmes" },
  { text: "Quantos minutos dura O Senhor dos Anéis: A Sociedade do Anel na versão de cinema?", answer: 178, unit: "minutos" },
  { text: "Quantos filmes compõem a Saga do Infinito do MCU?", answer: 23, unit: "filmes" },
  { text: "Em que ano Homem de Ferro iniciou o MCU nos cinemas?", answer: 2008, unit: "ano" },
  { text: "Quantos minutos dura Vingadores: Guerra Infinita?", answer: 149, unit: "minutos" },
  { text: "Quantos filmes há na trilogia De Volta para o Futuro?", answer: 3, unit: "filmes" },
  { text: "Em que ano Jurassic Park chegou aos cinemas?", answer: 1993, unit: "ano" },
  { text: "Quantos filmes compõem a saga principal Jogos Vorazes até A Cantiga dos Pássaros e das Serpentes?", answer: 5, unit: "filmes" },
  { text: "Em que ano o primeiro Toy Story foi lançado?", answer: 1995, unit: "ano" },
  { text: "Quantos minutos dura Divertida Mente 2?", answer: 96, unit: "minutos" },
  { text: "Quantos filmes compõem a trilogia original de Star Wars?", answer: 3, unit: "filmes" },

  // Séries e streaming (18)
  { text: "Quantos episódios tem Stranger Things até o fim da quarta temporada?", answer: 34, unit: "episódios" },
  { text: "Em que ano Stranger Things estreou?", answer: 2016, unit: "ano" },
  { text: "Quantos episódios tem Round 6 nas duas primeiras temporadas?", answer: 16, unit: "episódios" },
  { text: "Em que ano Round 6 estreou?", answer: 2021, unit: "ano" },
  { text: "Quantos episódios tem a série completa The Good Place?", answer: 53, unit: "episódios" },
  { text: "Quantas temporadas teve The Good Place?", answer: 4, unit: "temporadas" },
  { text: "Quantos episódios tem a série completa Dark?", answer: 26, unit: "episódios" },
  { text: "Quantas temporadas teve Dark?", answer: 3, unit: "temporadas" },
  { text: "Quantos episódios tem a série completa Brooklyn Nine-Nine?", answer: 153, unit: "episódios" },
  { text: "Quantas temporadas teve Brooklyn Nine-Nine?", answer: 8, unit: "temporadas" },
  { text: "Quantos episódios tem a série completa Succession?", answer: 39, unit: "episódios" },
  { text: "Quantas temporadas teve Succession?", answer: 4, unit: "temporadas" },
  { text: "Quantos episódios tem a minissérie O Gambito da Rainha?", answer: 7, unit: "episódios" },
  { text: "Quantos episódios tem a primeira temporada de Wandinha?", answer: 8, unit: "episódios" },
  { text: "Quantos episódios tem a primeira temporada de The Last of Us?", answer: 9, unit: "episódios" },
  { text: "Quantos episódios tem a série completa Peaky Blinders?", answer: 36, unit: "episódios" },
  { text: "Quantos episódios tem a série completa Better Call Saul?", answer: 63, unit: "episódios" },
  { text: "Quantos episódios tem a série completa La Casa de Papel na divisão original espanhola?", answer: 41, unit: "episódios" },

  // Música e celebridades (18)
  { text: "Quantas faixas tem a edição padrão do álbum Cowboy Carter?", answer: 27, unit: "faixas" },
  { text: "Quantas indicações ao Grammy Beyoncé acumulava após as nomeações de 2025?", answer: 99, unit: "indicações" },
  { text: "Quantas categorias Not Like Us venceu no Grammy de 2025?", answer: 5, unit: "categorias" },
  { text: "Qual foi o número da cerimônia do Grammy realizada em 2025?", answer: 67, unit: "ª edição" },
  { text: "Quantas faixas tem a edição padrão do álbum Short n' Sweet?", answer: 12, unit: "faixas" },
  { text: "Em que ano Taylor Swift lançou o álbum 1989?", answer: 2014, unit: "ano" },
  { text: "Quantas faixas tem a edição padrão original do álbum 1989?", answer: 13, unit: "faixas" },
  { text: "Em que ano Lady Gaga lançou Poker Face?", answer: 2008, unit: "ano" },
  { text: "Em que ano Beyoncé lançou Crazy in Love?", answer: 2003, unit: "ano" },
  { text: "Quantas faixas tem o álbum Thriller de Michael Jackson?", answer: 9, unit: "faixas" },
  { text: "Em que ano o álbum Thriller foi lançado?", answer: 1982, unit: "ano" },
  { text: "Quantos integrantes formavam os Beatles?", answer: 4, unit: "integrantes" },
  { text: "Em que ano os Beatles lançaram Abbey Road?", answer: 1969, unit: "ano" },
  { text: "Quantos integrantes formavam o grupo One Direction em sua formação original?", answer: 5, unit: "integrantes" },
  { text: "Em que ano Anitta lançou Show das Poderosas?", answer: 2013, unit: "ano" },
  { text: "Em que ano Marília Mendonça lançou o álbum ao vivo Realidade?", answer: 2017, unit: "ano" },
  { text: "Quantos integrantes tem a formação clássica dos Racionais MC's?", answer: 4, unit: "integrantes" },
  { text: "Em que ano os Racionais MC's lançaram Sobrevivendo no Inferno?", answer: 1997, unit: "ano" },

  // Jogos, animes e cultura geek (18)
  { text: "Em que ano o primeiro PlayStation foi lançado no Japão?", answer: 1994, unit: "ano" },
  { text: "Quantos bits tinha o processador principal do Super Nintendo?", answer: 16, unit: "bits" },
  { text: "Em que ano Minecraft teve seu lançamento completo?", answer: 2011, unit: "ano" },
  { text: "Em que ano Fortnite Battle Royale foi lançado?", answer: 2017, unit: "ano" },
  { text: "Quantos jogadores começam uma partida padrão de Fortnite Battle Royale?", answer: 100, unit: "jogadores" },
  { text: "Quantos tripulantes cabem numa partida clássica de Among Us após a expansão de 2021?", answer: 15, unit: "jogadores" },
  { text: "Quantos ginásios existem na região de Kanto nos primeiros jogos Pokémon?", answer: 8, unit: "ginásios" },
  { text: "Quantos Pokémon havia na primeira geração?", answer: 151, unit: "Pokémon" },
  { text: "Quantos episódios tem o anime Death Note?", answer: 37, unit: "episódios" },
  { text: "Quantos episódios tem Fullmetal Alchemist: Brotherhood?", answer: 64, unit: "episódios" },
  { text: "Quantas Esferas do Dragão são necessárias para invocar Shenlong?", answer: 7, unit: "esferas" },
  { text: "Quantos episódios tem a série original Dragon Ball?", answer: 153, unit: "episódios" },
  { text: "Quantos episódios tem Naruto sem contar Naruto Shippuden?", answer: 220, unit: "episódios" },
  { text: "Quantos episódios tem Naruto Shippuden?", answer: 500, unit: "episódios" },
  { text: "Quantos capítulos tem o mangá Demon Slayer?", answer: 205, unit: "capítulos" },
  { text: "Quantos lutadores havia no elenco inicial de Super Smash Bros. de Nintendo 64?", answer: 12, unit: "lutadores" },
  { text: "Quantas pistas havia no Mario Kart 64?", answer: 16, unit: "pistas" },
  { text: "Em que ano Grand Theft Auto V foi lançado originalmente?", answer: 2013, unit: "ano" },

  // Internet, aplicativos e tecnologia (18)
  { text: "Em que ano o YouTube foi fundado?", answer: 2005, unit: "ano" },
  { text: "Em que ano o primeiro vídeo foi publicado no YouTube?", answer: 2005, unit: "ano" },
  { text: "Quantos segundos dura o primeiro vídeo publicado no YouTube, Me at the zoo?", answer: 19, unit: "segundos" },
  { text: "Em que ano o Instagram foi lançado?", answer: 2010, unit: "ano" },
  { text: "Em que ano o WhatsApp foi fundado?", answer: 2009, unit: "ano" },
  { text: "Em que ano o TikTok foi lançado internacionalmente?", answer: 2017, unit: "ano" },
  { text: "Quantos caracteres tinha o limite original do Twitter?", answer: 140, unit: "caracteres" },
  { text: "Em que ano o Twitter aumentou o limite padrão para 280 caracteres?", answer: 2017, unit: "ano" },
  { text: "Em que ano o Facebook foi lançado?", answer: 2004, unit: "ano" },
  { text: "Em que ano a Netflix começou a oferecer streaming?", answer: 2007, unit: "ano" },
  { text: "Em que ano o Spotify foi lançado ao público?", answer: 2008, unit: "ano" },
  { text: "Em que ano a Wikipédia foi lançada?", answer: 2001, unit: "ano" },
  { text: "Quantos caracteres formam um endereço IPv4 completo em bits?", answer: 32, unit: "bits" },
  { text: "Quantos bits formam um byte?", answer: 8, unit: "bits" },
  { text: "Quantos dígitos tem um código PIN tradicional de celular?", answer: 4, unit: "dígitos" },
  { text: "Em que ano o primeiro iPhone foi lançado?", answer: 2007, unit: "ano" },
  { text: "Em que ano o sistema Android teve seu primeiro lançamento comercial?", answer: 2008, unit: "ano" },
  { text: "Quantos megabytes há em um gigabyte usando a convenção binária?", answer: 1024, unit: "MB" },

  // Esportes e grandes eventos (18)
  { text: "Quantas Copas do Mundo a seleção brasileira masculina venceu?", answer: 5, unit: "títulos" },
  { text: "Em que ano o Brasil venceu sua primeira Copa do Mundo masculina?", answer: 1958, unit: "ano" },
  { text: "Quantos gols foram marcados na goleada Alemanha 7 a 1 Brasil?", answer: 8, unit: "gols" },
  { text: "Quantos minutos dura uma prorrogação completa no futebol?", answer: 30, unit: "minutos" },
  { text: "Quantos jogadores formam um time de vôlei em quadra?", answer: 6, unit: "jogadores" },
  { text: "Quantos jogadores formam um time de basquete em quadra?", answer: 5, unit: "jogadores" },
  { text: "Quantos pontos vale uma cesta feita atrás da linha de três no basquete?", answer: 3, unit: "pontos" },
  { text: "Quantos sets um tenista precisa vencer numa partida masculina de Grand Slam?", answer: 3, unit: "sets" },
  { text: "Quantos quilômetros tem uma maratona oficial, arredondando para três casas decimais?", answer: 42.195, unit: "km" },
  { text: "Quantos segundos é o recorde mundial masculino dos 100 metros de Usain Bolt?", answer: 9.58, unit: "segundos" },
  { text: "Quantos anéis há no símbolo dos Jogos Olímpicos?", answer: 5, unit: "anéis" },
  { text: "Em que ano o Rio de Janeiro sediou os Jogos Olímpicos?", answer: 2016, unit: "ano" },
  { text: "Quantos títulos mundiais de Fórmula 1 Ayrton Senna conquistou?", answer: 3, unit: "títulos" },
  { text: "Em que ano Ayrton Senna conquistou seu primeiro título de Fórmula 1?", answer: 1988, unit: "ano" },
  { text: "Quantos jogadores formam uma dupla no vôlei de praia?", answer: 2, unit: "jogadores" },
  { text: "Quantos buracos possui uma volta padrão de golfe?", answer: 18, unit: "buracos" },
  { text: "Quantos rounds tem uma luta de boxe profissional por título mundial?", answer: 12, unit: "rounds" },
  { text: "Quantos pontos vale um touchdown no futebol americano antes do ponto extra?", answer: 6, unit: "pontos" },

  // Curiosidades, ciência e mundo (18)
  { text: "Quantos planetas existem no Sistema Solar?", answer: 8, unit: "planetas" },
  { text: "Quantas luas naturais Marte possui?", answer: 2, unit: "luas" },
  { text: "Quantos dias terrestres dura aproximadamente um ano em Marte?", answer: 687, unit: "dias" },
  { text: "Quantos minutos a luz do Sol leva aproximadamente para chegar à Terra?", answer: 8.3, unit: "minutos" },
  { text: "Quantos elementos químicos há oficialmente na tabela periódica?", answer: 118, unit: "elementos" },
  { text: "Quantos cromossomos possui normalmente uma célula humana?", answer: 46, unit: "cromossomos" },
  { text: "Quantos pares de cromossomos possui normalmente um ser humano?", answer: 23, unit: "pares" },
  { text: "Quantas câmaras tem o coração humano?", answer: 4, unit: "câmaras" },
  { text: "Quantas pernas tem uma lagosta?", answer: 10, unit: "pernas" },
  { text: "Quantos olhos simples e compostos uma abelha possui ao todo?", answer: 5, unit: "olhos" },
  { text: "Quantos braços tem uma estrela-do-mar mais comum?", answer: 5, unit: "braços" },
  { text: "Quantos lados tem um icoságono?", answer: 20, unit: "lados" },
  { text: "Quantos segundos existem em um dia?", answer: 86400, unit: "segundos" },
  { text: "Quantos dias possui um ano bissexto?", answer: 366, unit: "dias" },
  { text: "Quantos fusos horários teóricos de uma hora cobrem a Terra?", answer: 24, unit: "fusos" },
  { text: "Quantos quilômetros mede aproximadamente a circunferência da Terra no Equador?", answer: 40075, unit: "km" },
  { text: "Quantos metros acima do nível do mar mede oficialmente o Monte Everest?", answer: 8848.86, unit: "metros" },
  { text: "Quantos anos levou a missão New Horizons para chegar a Plutão, aproximadamente?", answer: 9.5, unit: "anos" },
];
